### ISSUE TITLE
In Follow Link mode, accept keys in any order

### ISSUE THREAD

**Issue by AndrewBelt** [akhodakivskiy/VimFx#694]
When hitting `f` on a page with many links, many yellow boxes of letters appear, some with as many as 3 characters, like `FJW`. Since the tags are not words, they are difficult to type correctly due to dyslexia. Perhaps typing a `J` should filter all the tags with that character, instead of tags *beginning* with that character.

While this theoretically decreases the size of the possible 1- and 2- character tags, for me, slamming three keys quickly is faster than typing one key after another. Hopefully this feature won't just benefit me.

**Comment by lydell** [comment]
If you have one link with the hint FJW and one with the hint J, how are you supposed to activate the J hint?

**Comment by AndrewBelt** [comment]
That's a good point, the space of possible tags is less than I initially thought then. What if all links are three letters (as needed)? Or tags are generated in such a way that this never happens (i.e. no tag is a subset of the characters of another)?

**Comment by lydell** [comment]
There are 19 hint chars by default.

If there are 19 links on a page, all of them will get a one-letter hint.

If there are 20 links, the current algorithm would produce 18 one-letter hints and 2 two-letter hints, while your proposal would generate _only_ two-letter hints.

There are 171 [combinations](https://en.wikipedia.org/wiki/Combination) of two-letter hints using the default hint chars. That means that if there are 172 links on a page, your proposal would generate _only_ three-letter hints, while the current algorithm would generate many two-letter hints and possible a few one-letter hints as well.

So to me, your proposal seems _worse_ for people with dyslexia, because it causes _more_ letters to type.

I suggest using the `g/` command as a complement to `f`, and using `<backspace>` in Hints mode whenever you make a mistake.

**Comment by AndrewBelt** [comment]
> because it causes more letters to type.

As above, I understand this. However, as I said, three letters would be easier to type than two in order. Regardless, I will probably work on this change for myself and publish it if people would like.

**Comment by lydell** [comment]
Yesterday I found a [dyslexia demo](http://geon.github.io/programming/2016/03/03/dsxyliea) that helped me understand the problem better.

Then I came up with a potential solution: What if each hint showed only one letter at a time? Then there’s no way you can mix the letters of a shortcut up.

The above can be achived with the following custom [styling](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/styling.md):

```css
#VimFxMarkersContainer .marker-char:not(.marker-char--matched),
#VimFxMarkersContainer .marker-char.marker-char--matched {
  opacity: 0 !important;
}

#VimFxMarkersContainer .marker-char:not(.marker-char--matched):first-child,
#VimFxMarkersContainer .marker-char.marker-char--matched + .marker-char:not(.marker-char--matched) {
  opacity: 1 !important;
}
```

You could also try to experiment with an opacity such as `0.1`.

(I’ve written the above code a bit more verbosely than technically needed to make it easier to understand and adapt.)
